OUTSIDE

diff --git a/.github/workflows/deploy-repo-pull_request.yml b/.github/workflows/deploy-repo-pull_request.yml
--- a/.github/workflows/deploy-repo-pull_request.yml
+++ b/.github/workflows/deploy-repo-pull_request.yml
@@ -32,12 +32,7 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v3
 
-      - id: auth
-        name: Authenticate to Google Cloud
-        uses: "google-github-actions/auth@v0"
-        with:
-          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
-          service_account: ${{ vars.SERVICE_ACCOUNT }}
+
 
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v2
@@ -89,62 +84,62 @@ jobs:
             echo "Terraform plan shows no resources being created, updated or deleted"
           fi
 
-      - name: Add sticky PR comment
-        id: pr_comment_sticky
-        uses: mshick/add-pr-comment@v2
-        if: github.event_name == 'pull_request'
-        env:
-          PLAN: ${{ steps.plan_output.outputs.stdout }}
-          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
-        with:
-          message: |
-            #### Terraform Automated Plan 📖 ${{ steps.plan_output.outcome }}
-            <details><summary>Show Plan (Current Status of Pull Request)</summary>
-
-            ```terraform
-            ${{ env.PLAN }}
-            ```
-
-            </details>
-
-      - name: Terraform plan status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
-
-      - name: Check if updating repos and PR not approved or using main
-        if: contains(steps.plan_check.outputs.PLAN_CHECK, 'UPDATE_DESTROY') && github.event.review.state != 'approved' && github.ref != 'refs/heads/main'
-        run: exit 0
-
-      # - name: Terraform apply
-      #   if: github.event.review.state == 'approved' || github.ref == 'refs/heads/main'
-      #   id: apply
-      #   run: terraform apply -auto-approve -input=false tfplan.json -no-color
-      #   env:
-      #     GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
-
-      # - name: Add/update comment to the PR with the Apply output
-      #   id: pr_comment_apply
-      #   if: github.event_name == 'pull_request_review' && steps.apply.outcome == 'success'
+      # - name: Add sticky PR comment
+      #   id: pr_comment_sticky
       #   uses: mshick/add-pr-comment@v2
+      #   if: github.event_name == 'pull_request'
       #   env:
-      #     GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
       #     PLAN: ${{ steps.plan_output.outputs.stdout }}
-      #     APPLY: ${{ steps.apply.outputs.stdout }}
+      #     GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
       #   with:
-      #     allow-repeats: true
       #     message: |
-      #       #### Terraform Automated Apply 📖 ${{ steps.apply.outcome }}
-      #       <details><summary>Show Original Plan</summary>
+      #       #### Terraform Automated Plan 📖 ${{ steps.plan_output.outcome }}
+      #       <details><summary>Show Plan (Current Status of Pull Request)</summary>
 
       #       ```terraform
       #       ${{ env.PLAN }}
       #       ```
 
       #       </details>
-      #       <details><summary>Show Apply Output</summary>
 
-      #       ```terraform
-      #       ${{ env.APPLY }}
-      #       ```
+      # - name: Terraform plan status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
 
-      #       </details>
+      # - name: Check if updating repos and PR not approved or using main
+      #   if: contains(steps.plan_check.outputs.PLAN_CHECK, 'UPDATE_DESTROY') && github.event.review.state != 'approved' && github.ref != 'refs/heads/main'
+      #   run: exit 0
+
+      # # - name: Terraform apply
+      # #   if: github.event.review.state == 'approved' || github.ref == 'refs/heads/main'
+      # #   id: apply
+      # #   run: terraform apply -auto-approve -input=false tfplan.json -no-color
+      # #   env:
+      # #     GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
+
+      # # - name: Add/update comment to the PR with the Apply output
+      # #   id: pr_comment_apply
+      # #   if: github.event_name == 'pull_request_review' && steps.apply.outcome == 'success'
+      # #   uses: mshick/add-pr-comment@v2
+      # #   env:
+      # #     GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
+      # #     PLAN: ${{ steps.plan_output.outputs.stdout }}
+      # #     APPLY: ${{ steps.apply.outputs.stdout }}
+      # #   with:
+      # #     allow-repeats: true
+      # #     message: |
+      # #       #### Terraform Automated Apply 📖 ${{ steps.apply.outcome }}
+      # #       <details><summary>Show Original Plan</summary>
+
+      # #       ```terraform
+      # #       ${{ env.PLAN }}
+      # #       ```
+
+      # #       </details>
+      # #       <details><summary>Show Apply Output</summary>
+
+      # #       ```terraform
+      # #       ${{ env.APPLY }}
+      # #       ```
+
+      # #       </details>
